export const ORDER_STATUS = {
  PENDING_PAYMENT: 'PENDING_PAYMENT',
  CONFIRMED: 'CONFIRMED',
  PROCESSING: 'PROCESSING',
  IN_PRODUCTION: 'IN_PRODUCTION',
  WAREHOUSE_RECEIVED: 'WAREHOUSE_RECEIVED',
  QC_IN_PROGRESS: 'QC_IN_PROGRESS',
  QC_FAILED: 'QC_FAILED',
  PACKING: 'PACKING',
  DISPATCHED: 'DISPATCHED',
  DELIVERED: 'DELIVERED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  FAILED: 'FAILED',
} as const;

export type OrderStatus = (typeof ORDER_STATUS)[keyof typeof ORDER_STATUS];

export const ORDER_TRANSITIONS: Record<string, string[]> = {
  PENDING_PAYMENT: ['CONFIRMED', 'FAILED', 'CANCELLED'],
  CONFIRMED: ['PROCESSING', 'CANCELLED'],
  PROCESSING: ['WAREHOUSE_RECEIVED', 'IN_PRODUCTION', 'CANCELLED'],
  IN_PRODUCTION: ['WAREHOUSE_RECEIVED', 'CANCELLED'],
  WAREHOUSE_RECEIVED: ['QC_IN_PROGRESS'],
  QC_IN_PROGRESS: ['PACKING', 'QC_FAILED'],
  QC_FAILED: ['WAREHOUSE_RECEIVED', 'CANCELLED'],
  PACKING: ['DISPATCHED'],
  DISPATCHED: ['DELIVERED'],
  DELIVERED: ['COMPLETED'],
  COMPLETED: [],
  CANCELLED: [],
  FAILED: [],
};

export const PRODUCT_TYPE = {
  READY_STOCK: 'READY_STOCK',
  MADE_TO_ORDER: 'MADE_TO_ORDER',
  ON_DEMAND: 'ON_DEMAND',
} as const;

export type ProductType = (typeof PRODUCT_TYPE)[keyof typeof PRODUCT_TYPE];

export const PRODUCT_STATUS = {
  DRAFT: 'DRAFT',
  PENDING_APPROVAL: 'PENDING_APPROVAL',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  DISABLED: 'DISABLED',
} as const;

export type ProductStatus = (typeof PRODUCT_STATUS)[keyof typeof PRODUCT_STATUS];

export const RETURN_REASON = {
  DEFECTIVE: 'DEFECTIVE',
  WRONG_ITEM: 'WRONG_ITEM',
  TRANSIT_DAMAGE: 'TRANSIT_DAMAGE',
  PREFERENCE_CHANGE: 'PREFERENCE_CHANGE',
  OTHER: 'OTHER',
} as const;

export type ReturnReason = (typeof RETURN_REASON)[keyof typeof RETURN_REASON];

export const SELLER_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  SUSPENDED: 'SUSPENDED',
  REJECTED: 'REJECTED',
} as const;

export type SellerStatus = (typeof SELLER_STATUS)[keyof typeof SELLER_STATUS];

export const RETURN_POLICY = {
  DEFECT_ONLY: 'DEFECT_ONLY',
  NO_RETURN: 'NO_RETURN',
  STANDARD: 'STANDARD',
} as const;

export type ReturnPolicy = (typeof RETURN_POLICY)[keyof typeof RETURN_POLICY];

// Return eligibility matrix: product type -> allowed return reasons
export const RETURN_ELIGIBILITY: Record<string, string[]> = {
  READY_STOCK: ['DEFECTIVE', 'WRONG_ITEM', 'TRANSIT_DAMAGE'],
  MADE_TO_ORDER: ['DEFECTIVE', 'WRONG_ITEM', 'TRANSIT_DAMAGE'],
  ON_DEMAND: ['DEFECTIVE', 'WRONG_ITEM', 'TRANSIT_DAMAGE'],
};

export const RETURN_WINDOW_DAYS = 7;
